# ------------ Build processing ------------

[build]
  publish = "dist/"
  command = "npm run generate"

# ------------ Asset processing ------------

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = true

# ------------ Redirects ------------

[[redirects]]
  from = "/single-post"
  to = "/post?=:domain&id=:id" 
  # status = 301
  force = true
  query = {domain = ":domain", id = ":id"}

# https://r34.app/single-post?id=100&domain=xxx