[phases.setup]
nixPkgs = ['...', 'python3']
# TODO: Fix for Node 22.19 not available in latest nixpkgs - https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=nodejs
nixpkgsArchive = '3042376469d8940a95b7294273fdbf1fa0d0ec67'
